# This is auto-generated by fa_helper.py
fa_icons = \
{   'angles-right': '\uf101',
    'caret-down': '\uf0d7',
    'circle': '\uf111',
    'circle-dot': '\uf192',
    'clipboard-check': '\uf46c',
    'plus': '+',
    'square': '\uf0c8',
    'square-check': '\uf14a'}
